### PR TITLE
#137 fix: v2 Toast not dismissing after timeout

### PR DESCRIPTION
**Pull request by emresudo**
# Emitter naming problem fixed

## Description
There was a problem in triggering the transaction in the Vue 3 project as the name of the transmitter was made with a kebab case.
Naming changed and tested by me in Vue-3.0.0 project to a proper format, it works fine.

## Related Issue
[Issue: #137 ](https://github.com/Maronato/vue-toastification/issues/137)

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/Maronato/vue-toastification/blob/master/CONTRIBUTING.md) document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by restyler** [comment]
Thank you for the PR! I am not a maintainer of this library, but just my 2 cents:  to avoid delays in Code Review & merging, you should remove excess and opinionated formatting changes (semicolon removals) from your PR branch.

**Comment by emresudo** [comment]
> Thank you for the PR! I am not a maintainer of this library, but just my 2 cents: to avoid delays in Code Review & merging, you should remove excess and opinionated formatting changes (semicolon removals, spacing changes) from your PR branch.

Thank you for your answer. There are some changes I missed, I fixed them and added them as commit.

**Review by restyler — APPROVED** [review]
Looks good to me.

**Comment by Maronato** [comment]
Hello, @emresudo ! Thank you for the PR. It looks great, but I think [I've found](https://github.com/Maronato/vue-toastification/issues/137#issuecomment-716039771) what the underlying issue is.

I'll push my proposed fix first, so you guys can test it out and if it is not enough, I'll merge your PR.

**Comment by Maronato** [comment]
Closing this since #139 seems to have fixed #137.
Thank you @emresudo anyway for submitting the PR!

**Pull request closed without merging**
