### PR TITLE
Add Fade in/Out and Slide in/out Blurred transitions

### PR DESCRIPTION
**Pull request by connecteev**
Added 2 custom professional-looking transitions, the ones that aren't too cheesy :)

### CODE REVIEW

**Comment by connecteev** [comment]
Removed the package-lock.json. I'm not sure where you want the documentation, it doesnt make sense to add to the demo page and I feel like it's self-explanatory with the nice example you have on the right showing code usage.
If you still want doc changes, would you mind making them yourself to the PR so I can see what you mean for next time?

**Comment by connecteev** [comment]
@Maronato added with documentation...let me know if looks good!

**Comment by Maronato** [comment]
Sorry about the delay, @connecteev 
Looks great, thanks for the contribution!

**Comment by connecteev** [comment]
@Maronato great! look fwd to seeing this improve and the other changes proposed make it in as well

**Pull request merged**
